[lints.clippy]
needless_return = "allow"

[package]
name = "chip_8_emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
minifb = "0.28.0"
rand = "0.9.0"
rodio = "0.20.1"
single_value_channel = "1.2.2"
u4 = "0.1.2"
